name: Deploy to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches: main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install `pnpm` via Corepack
        run: corepack enable
      - name: Install Dependencies
        run: pnpm install
      - name: Check Formatters
        run: pnpm fmt
      - name: Check HTML
        run: pnpm lint:html
      - name: Check CSS
        run: pnpm lint:css
      - name: Synchronize SvelteKit
        run: pnpm sync
      - name: Check JavaScript
        run: pnpm lint:js
      - name: Check Svelte
        run: pnpm lint:svelte
      - name: Build Website
        run: pnpm build
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: build
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
